### ISSUE TITLE
How to visual test results?

### ISSUE THREAD

**Issue by 17000432** [gcollell/spatial-commonsense#1]
How to test a picture to predict the visualization of spatial relationship results?Thanks

**Comment by gcollell** [comment]
You can set the argument save_indiv_predictions as True and an output file with what you are asking will be generated. This contains both, the predicted object coordinates and the ground truth ones for specific test instances. You can then visualize them with your favorite visualization function.

**Comment by matsaliu** [comment]
![1](https://user-images.githubusercontent.com/59641070/75377227-fcedc100-5896-11ea-9d84-cdbae3947ce7.PNG)

**Comment by matsaliu** [comment]
![1](https://user-images.githubusercontent.com/59641070/75377263-09721980-5897-11ea-9404-e89bc6f7dab7.PNG)


Having this error while executing. Please respond.

**Comment by gcollell** [comment]
Please look at file names. You need to create the folder ../training_data manually

**Comment by matsaliu** [comment]
![1](https://user-images.githubusercontent.com/59641070/75615610-9a512b00-5b0b-11ea-9ec5-1b29e8d6e034.PNG)
I'm sorry to disturb you, please. I'm implementing this paper in one of our courses. After your last email, I implemented accordingly but permission have been denied to the visualgenome/relationships_v1_2.json

**Comment by gcollell** [comment]
Sorry, I can't help you with that, as this problem is related to the file permissions in your local machine. You may try using a different folder or machine. The file relationships_v1_2.json has no issues.

**Comment by matsaliu** [comment]
Thank you, i'm getting through gradually.  

Sent from Yahoo Mail on Android 
 
  On Wed., 4 Mar. 2020 at 4:19 p.m., Guillem Collell<notifications@github.com> wrote:   
Sorry, I can't help you with that, as this problem is related to the file permissions in your local machine. You may try using a different folder or machine. The file relationships_v1_2.json has no issues.
